### ISSUE TITLE
Mixin errors with BYG (?)

### ISSUE THREAD

**Issue by LiskoSlayer63** [CorgiTaco-Archive/Upstream#9]
Noticed that you are the same creator for Upstream and BYG, right?

I noticed this in the server console:
```
[13:31:12] [main/ERROR] [mixin/CATCHING]: Catching
java.lang.ClassNotFoundException: corgiaoc.byg.mixin.MixinConnector
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:57) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:71) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:60) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97) ~[modlauncher-8.0.9.jar:?]
	at java.util.HashMap.forEach(Unknown Source) [?:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:128) [mohist-1.16.5-785-server.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:125) [mohist-1.16.5-785-server.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:109) [mohist-1.16.5-785-server.jar:?]
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
		at java.lang.Class.forName0(Native Method) ~[?:?]
		at java.lang.Class.forName(Unknown Source) ~[?:?]
		at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:57) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:71) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:60) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97) ~[modlauncher-8.0.9.jar:?]
		at java.util.HashMap.forEach(Unknown Source) [?:?]
		at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
		at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:128) [mohist-1.16.5-785-server.jar:?]
		at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:125) [mohist-1.16.5-785-server.jar:?]
		at net.minecraftforge.server.ServerMain.main(ServerMain.java:109) [mohist-1.16.5-785-server.jar:?]
```
I firstly thought that it was BYG's error, but some Googling took me to CorgiTaco/BYG#520 and there you were mentioned that this is Upstreams problem. However, there appears not to be any issues opened here about the situation, so now here is.

**Comment by ShibeTemple** [comment]
I am also experiencing this issue

**Comment by criscky** [comment]
idk what that can imply, but it seems that file was removed from oh biomes you go in here
https://github.com/AOCAWOL/BYG/commit/0f7705869867e25577b18b933948a459a2c788d8
but it's still being "used" in here in upstreams
https://github.com/CorgiTaco/Upstream/blob/7411217735f8a3be2a45268762835b2df6578208/build.gradle#L96

even tho this file exist
https://github.com/CorgiTaco/Upstream/blob/Forge-1.16.X/src/main/java/corgitaco/upstream/mixin/MixinConnector.java
maybe it's referencing the wrong file?

**Comment by DaemonUmbra** [comment]
That file was no longer required in BYG and was only referenced in Upstream because of a copy/paste blunder from when it was required
<details>
<summary>Rant</summary>
The solution is to simply delete one line in build.gradle and I have brought this up with CorgiTaco before and they refuse to "fix what isn't broken" even though it is broken it's just that Mixin is happily swallowing the error with a bit of log spam instead of crashing the game.
</details>
